---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes.openziti.io
  resources:
  - ziticontrollers
  - zitirouters
  - zitiwebhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes.openziti.io
  resources:
  - ziticontrollers/finalizers
  - zitirouters/finalizers
  - zitiwebhooks/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetes.openziti.io
  resources:
  - ziticontrollers/status
  - zitirouters/status
  - zitiwebhooks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
