# permissions for end users to view zitiwebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ziti-operator
    app.kubernetes.io/managed-by: kustomize
  name: zitiwebhook-viewer-role
rules:
- apiGroups:
  - kubernetes.openziti.io
  resources:
  - zitiwebhooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubernetes.openziti.io
  resources:
  - zitiwebhooks/status
  verbs:
  - get
