apiVersion: kubernetes.openziti.io/v1alpha1
kind: ZitiController
metadata:
  labels:
    app.kubernetes.io/name: ziti-operator
    app.kubernetes.io/managed-by: kustomize
  name: ziticontroller-sample
  namespace: ziti
spec:
  name: ziticontroller-sample
  adminJwt: eyJhbGciOiJSUzI1NiIsImtpZCI6ImI0NWFmYWQ1NzFiNDM1NjBkNDU2Y2JjYjI4YzBlZjkwZDgzYzQ2ZTIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovLzhlZDE1YmVhLTU2MDMtNDg1ZS04NTc5LWEyOTcxZDJkYTY4NC5wcm9kdWN0aW9uLm5ldGZvdW5kcnkuaW86NDQzIiwic3ViIjoiWUk3aXIyWkdUbiIsImF1ZCI6WyIiXSwiZXhwIjoxNzQyMjY2MzQxLCJqdGkiOiI0YjNmZjFiZC1hYjJjLTRiOWYtYjQ0Yi0zZjZjOTkwNWZmZWMiLCJlbSI6Im90dCIsImN0cmxzIjpudWxsfQ.BhyAGv_E9P0NYF8tJjDWyXeXHNKAfMmSeBHpa_J0Qs3TSrhWA1-u3BMxtYvCk9zpMgm50Ft3StCxPahgveTT3w40yBgd-uZ8uHRQle5pUkbhXn8g9E5LgAN5ImyFLUVI_vaG-xqJ8uHKG5ScWUU3z7bHVqoURCrlVSwBBF_iw27DA4o3AYTtDvGk7Y5Jbv_4hdyXGHghMoH1rrP0puENYYgLRSk3q9Y4pClk874uA6e_e3SkX_YsxzDVSiFStFAalOce9EpxP_ngN7Cy1Tu7vWAKgCBoYkf5I0AEBRR95yS838cOXqWW25ZK414nj5HYi00_OuzXA4aAQnrYqAsAohVOcDBXzdbDF7jl_oJZWZOeX17YXBXQbdVuA9Ss72vt090oW3_SZhx4zn3k7XRnT6B09kBNF7qNKNdYCAAfL3s0eQgQHp2ZBRaxmjtzbrKNiipREMygBI_B3XPViVhhdDgMtMAkVjvQjeZjsYyGChipFINlCtJjT9BY8Ls3zOWnEXBl35rsu2KIZBMijlZwWTWODoUs46-aoTcCTNyo-_4Clb1M_3-RSYRe41MOZd4TgTJCOTrwUZ5e3l70i2d5qmL6KpRzZ8ONIypmZWS_RIXC_dunyEwriK_G_CMwwWYmWLmvvO4oy0Opzbjl54Fn2lWZLJgHLOTB7Vgr3MHa6Z4
