apiVersion: kubernetes.openziti.io/v1alpha1
kind: ZitiController
metadata:
  labels:
    app.kubernetes.io/name: ziti-operator
    app.kubernetes.io/managed-by: kustomize
  name: ziticontroller-sample
  namespace: ziti
spec:
  name: ziticontroller-sample
  adminJwt: eyJhbGciOiJSUzI1NiIsImtpZCI6ImI0NWFmYWQ1NzFiNDM1NjBkNDU2Y2JjYjI4YzBlZjkwZDgzYzQ2ZTIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovLzhlZDE1YmVhLTU2MDMtNDg1ZS04NTc5LWEyOTcxZDJkYTY4NC5wcm9kdWN0aW9uLm5ldGZvdW5kcnkuaW86NDQzIiwic3ViIjoiWUk3aXIyWkdUbiIsImF1ZCI6WyIiXSwiZXhwIjoxNzQ2MzE3MzU0LCJqdGkiOiI4NzNjNDE4MS03NTM5LTQyMzAtYjE2MC1jZTMxNmFiYzhlZGMiLCJlbSI6Im90dCIsImN0cmxzIjpudWxsfQ.KmaPdqzAbSbrDS-AVtcGbWZnMz-gJuxcf6eE_TI9fSXUanG2WRvfvCxpj6BQj2XE2Q2dAo6aFU2d7zqvBrg4SDY2QjrTKAAIkDQTeV9dq8lAqFCQeYP7QHeyIv5MGaNYgbJkFDlxL3UCfhOEo7TQgTVdAJ4FCvg8kB_xCQ96_x9cHShDQWWNlkOW0SNc019Rqudna7vf-frX5CyLbRtOj29mv7KZBbl0VNirhme7ML93GFErmJqJCAxBkYzfmmAdCSZ3g7AiQsZq1ORPWeiHBF-hEDT7xDRXSvJHdY-W6cLUebuRjXW35jZsGArmUMz60qFymIHty9pIjBXyW9J5kgQ-c20nJg42K8Aseen2_1QeVcVOIGxrkjHV8rdtbFPEQTEFOB-Ml64RKq09L2s3G9sP-991RQ84w44yTR4ulz0szA9WJHUgZ5HvYMspYpz2sgekTl9UYppHpFFtBhipnNJA6Eb6koTgOrF8i9xQROqNH1ZOBn-aSdqqSJduC8jQxVPDPkvhRVcno4gKuQd__8Mo3t1tbxqOYDoGjN-pBchIrPz7LgrWShasOOA4yQFFVvaQS8d82DA2v8MfP6WVFSdeg5xXDpWftmixAA6UG6xqbAy2O1Mn35n5Ax9r2QXiEuSXXvJOpqCyqk9Mv0DPUjLe-EkD3GCanQpVDNrpS-0
  zitiCtrlMgmtApi: https://8ed15bea-5603-485e-8579-a2971d2da684.production.netfoundry.io:443/edge/management/v1
  